module.exports.authController = require('./auth.controller')
module.exports.configurationController = require('./configuration.controller')
module.exports.notificationController = require('./notification.controller')
module.exports.roleController = require('./role.controller')
module.exports.userController = require('./user.controller')